todo/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [ 
    path("", include("task.urls")), 
    path("crontab_manager/", include("django_crontab_manager.urls")), 
    path("admin/", admin.site.urls)
]

todo/task/urls.py
from django.urls import path


app_name = "task"

#########################################################
# Raw views
#########################################################

from .views import (
    TaskCreateRawView,
    TaskDeleteRawView,
    TaskDetailRawView,
    TaskListRawView,
    TaskUpdateRawView,
)

urlpatterns = [
    path("", TaskListRawView.as_view(), name="index"),
    path("create/", TaskCreateRawView.as_view(), name="create"),
    path("update/<int:id>/", TaskUpdateRawView.as_view(), name="update"),
    path("delete/<int:id>/", TaskDeleteRawView.as_view(), name="delete"),
    path("detail/<int:id>/", TaskDetailRawView.as_view(), name="detail"),
]

# #########################################################
# # Classes based views
# #########################################################

# from .views (
#     TaskCreateView,
#     TaskDeleteView,
#     TaskDetailView,
#     TaskListView,
#     TaskUpdateView
# )

# urlpatterns = [
#     path('', TaskListView.as_view(), name='index'),
#     path('create/', TaskCreateView.as_view(), name='create'),
#     path('update/<int:id>/', TaskUpdateView.as_view(), name='update'),
#     path('delete/<int:id>/', TaskDeleteView.as_view(), name='delete'),
#     path('detail/<int:id>/', TaskDetailView.as_view(), name='detail')
# ]

#########################################################
# Functions based Views
#########################################################

# from .views (
#     list_view,
#     create_view,
#     create_view_raw,
#     update_view ,
#     delete_view,
#     detail_view
# )

# urlpatterns = [
#     path('', list_view, name='index'),
#     path('create/', create_view, name='create'),
#     path('createraw/', create_view_raw, name='createraw'),
#     path('update/<int:id>/', update_view, name='update'),
#     path('delete/<int:id>/', delete_view, name='delete'),
#     path('detail/<int:id>/', detail_view, name='detail')
# ]

todo/apps/task/models/tag_repository.py
from .tag import Tag
from .repository import DjangoRepository


class TagRepository(DjangoRepository):
    def __init__(self) -> None:
        super().__init__(Tag)

todo/apps/task/models/task_repository.py
from .task import Task
from .repository import DjangoRepository


class TaskRepository(DjangoRepository):
    def __init__(self) -> None:
        super().__init__(Task)

todo/task/models/tag.py
from django.db import models
from django.urls import reverse

from utils.models import CreationModificationDateMixin


class Tag(CreationModificationDateMixin):
    """Tag's model class."""

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    slug = models.SlugField(max_length=50, unique=True, blank=False)

    def __str__(self) -> str:
        return self.slug

    def get_absolute_url(self, *args, **kwargs):
        return reverse("task:detail", kwargs={"id": self.id})

todo/task/forms.py
from django import forms
from django.utils import timezone

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "deadline_at",
            "finished_at",
            "tags",
        ]

    title = forms.CharField(
        label="Task Title",
        widget=forms.TextInput(attrs={"placeholder": "The Task Title"}),
        error_messages={"required": "Please Enter The Task Title"},
    )
    description = forms.CharField(
        label="Description",
        required=False,
        widget=forms.Textarea(
            attrs={
                "class": "class-name-1 class-name-1",
                "id": "id-for-textarea",
                "rows": 4,
                "cols": 25,
                "placeholder": "The Task Description",
            }
        ),
    )

    deadline_at = forms.DateTimeField(
        # format of datetime-local: yyyy-MM-ddThh:mm
        input_formats=["%Y-%m-%dT%H:%M"],
        label="Deadline",
        widget=forms.DateTimeInput(
            attrs={
                "type": "datetime-local",
            },
            format="%Y-%m-%dT%H:%M",
        ),
    )

    finished_at = forms.DateTimeField(
        required=False,
        # format of datetime-local: yyyy-MM-ddThh:mm
        input_formats=["%Y-%m-%dT%H:%M"],
        label="Finished",
        widget=forms.DateTimeInput(
            attrs={
                "type": "datetime-local",
            },
            format="%Y-%m-%dT%H:%M",
        ),
    )

    # def clean_deadline_at(self, *args, **kwargs):
    #     """ Example of validate method.
    #
    #     Evaluating if the deadline datetime is greater than current time
    #     """
    #
    #     deadline_at = self.cleaned_data.get("deadline_at")
    #     if not self.instance.pk:
    #         if deadline_at <= timezone.now():
    #             raise forms.ValidationError(
    #                 "This is not a valid deadline time.")
    #     return deadline_at


class RawTaskForm(forms.Form):
    title = forms.CharField(
        label="Task Title",
        widget=forms.TextInput(attrs={"placeholder": "The Task Title"}),
    )

    description = forms.CharField(
        label="Description",
        required=False,
        widget=forms.Textarea(
            attrs={
                "class": "class-name-1 class-name-1",
                "id": "id-for-textarea",
                "rows": 4,
                "cols": 25,
                "placeholder": "The Task Description",
            }
        ),
    )

    deadline_at = forms.DateTimeField(
        # format of datetime-local: yyyy-MM-ddThh:mm
        input_formats=["%Y-%m-%dT%H:%M"],
        label="Deadline",
        widget=forms.DateTimeInput(
            attrs={
                "type": "datetime-local",
            },
            format="%Y-%m-%dT%H:%M",
        ),
    )

    finished_at = forms.DateTimeField(
        required=False,
        # format of datetime-local: yyyy-MM-ddThh:mm
        input_formats=["%Y-%m-%dT%H:%M"],
        label="Finished",
        widget=forms.DateTimeInput(
            attrs={
                "type": "datetime-local",
            },
            format="%Y-%m-%dT%H:%M",
        ),
    )

    # def clean_deadline_at(self, *args, **kwargs):
    #     """ Example of validate method.
    #
    #     Evaluating if the deadline datetime is greater than current time
    #     """
    #
    #     deadline_at = self.cleaned_data.get("deadline_at")
    #     if not self.instance.pk:
    #         if deadline_at <= timezone.now():
    #             raise forms.ValidationError(
    #                 "This is not a valid deadline time.")
    #     return deadline_at

todo/task/views/classes_based_views.py
""" Classes based Views """

from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django.shortcuts import get_object_or_404, HttpResponseRedirect, Http404

from task.forms import TaskForm
from task.models import Task


class TaskListView(ListView):  # pragma: no cover
    """ListView"""

    template_name = "task/task_list.html"
    queryset = Task.objects.all()


class TaskCreateView(CreateView):  # pragma: no cover
    """CreateView"""

    template_name = "task/task_create.html"
    form_class = TaskForm
    queryset = Task.objects.all()

    # Change the success url. If there's a get_absolute_url()
    # method in the model this will be ignored.
    # success_url = "/"

    def form_valid(self, form):
        """DetailView.get_object() method"""

        print(form.cleaned_data)
        return super().form_valid(form)

    def get_success_url(self) -> str:
        """
        Another way to change the success url. If there's a
        get_absolute_url() method in the model this will be ignored.
        """
        return reverse("task:index")


class TaskUpdateView(UpdateView):  # pragma: no cover
    """UpdateView"""

    template_name = "task/task_create.html"
    form_class = TaskForm

    def form_valid(self, form):
        """DetailView.get_object() method"""

        print(form.cleaned_data)
        return super().form_valid(form)

    def get_object(self):
        """
        Overwrite UpdateView get_object() method
        to get the 'id' argument instead of 'pk'
        default argument.
        """

        _id = self.kwargs.get("id")
        return get_object_or_404(Task, id=_id)


class TaskDeleteView(DeleteView):  # pragma: no cover
    """DeleteView"""

    template_name = "task/task_delete.html"

    def get_object(self):
        """
        Overwrite UpdateView get_object() method
        to get the 'id' argument instead of 'pk'
        default argument.
        """

        _id = self.kwargs.get("id")
        return get_object_or_404(Task, id=_id)

    def get_success_url(self):
        return reverse("task:index")


class TaskDetailView(DetailView):  # pragma: no cover
    """DetailView"""

    template_name = "task/task_detail.html"

    def get_object(self):
        """
        Overwrite UpdateView get_object() method
        to get the 'id' argument instead of 'pk'
        default argument.
        """

        _id = self.kwargs.get("id")
        return get_object_or_404(Task, id=_id)

todo/task/views/function_views.py
""" Functions based Views """

from django.urls import reverse
from django.shortcuts import Http404, HttpResponseRedirect, get_object_or_404, render

from task.forms import TaskForm, RawTaskForm
from task.models import Task


def list_view(request, *args, **kwargs):  # pragma: no cover
    """ """
    view_context = {"object_list": [task for task in Task.objects.all()]}
    return render(request, "task/task_list.html", view_context)


def create_view(request, *args, **kwargs):  # pragma: no cover
    """Using built-in django form"""

    form = TaskForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("task:index"))

    view_context = {"form": form}
    return render(request, "task/task_create.html", view_context)


def create_view_raw(request, *args, **kwargs):  # pragma: no cover
    """Creating a raw django form"""

    if request.method == "POST":
        form = RawTaskForm(request.POST)
        if form.is_valid():
            Task.objects.create(**form.cleaned_data)
            return HttpResponseRedirect(reverse("task:index"))
        else:
            print(form.errors)
    elif request.method == "GET":
        form = RawTaskForm()
        view_context = {"form": form}
        return render(request, "task/task_create.html", view_context)

    Http404()


def update_view(request, id, *args, **kwargs):  # pragma: no cover
    """Using built-in django form"""

    # # Option 1
    # try:
    #     obj = Task.objects.get(id=id)
    # except Task. DoesNotExist:
    #     raise Http404

    # # Option 2
    # try:
    #     obj = Task.objects.get(id=id)
    # except Task.DoesNotExist:
    #     return HttpResponseNotFound("Not found")

    # Option 3
    obj = get_object_or_404(Task, id=id)

    if request.method == "POST":
        form = TaskForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(obj.get_absolute_url())
    elif request.method == "GET":
        form = TaskForm(None, instance=obj)
        view_context = {"form": form}
        return render(request, "task/task_create.html", view_context)

    Http404()


def delete_view(request, id, *args, **kwargs):  # pragma: no cover
    """ """

    # # Option 1
    # try:
    #     obj = Task.objects.get(id=id)
    # except Task. DoesNotExist:
    #     raise Http404

    # # Option 2
    # try:
    #     obj = Task.objects.get(id=id)
    # except Task.DoesNotExist:
    #     return HttpResponseNotFound("Not found")

    # Option 3
    obj = get_object_or_404(Task, id=id)

    if request.method == "POST":
        obj.delete()
        print(reverse("task:index"))
        return HttpResponseRedirect(reverse("task:index"))
    elif request.method == "GET":
        view_context = {"object": obj}
        return render(request, "task/task_delete.html", view_context)

    Http404()


def detail_view(request, id, *args, **kwargs):  # pragma: no cover
    """ """

    # # Option 1
    # try:
    #     obj = Task.objects.get(id=id)
    # except Task. DoesNotExist:
    #     raise Http404

    # # Option 2
    # try:
    #     obj = Task.objects.get(id=id)
    # except Task.DoesNotExist:
    #     return HttpResponseNotFound("Not found")

    # Option 3
    obj = get_object_or_404(Task, id=id)

    view_context = {"object": obj}
    return render(request, "task/task_detail.html", view_context)

todo/task/views/raw_views_classes.py
""" Raw views """

from django.contrib import messages
from django.core.paginator import Paginator
from django.db import transaction
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import View

from utils.forms import DivErrorList

from task.services import add_task_service, update_task_service, detele_task_service
from task.adapters import TaskRepository
from task.forms import TaskForm


class TaskObjectMixin(object):
    model = TaskRepository().model

    def get_object(self):
        id = self.kwargs.get("id")
        obj = None
        if id is not None:  # pragma: no cover
            obj = get_object_or_404(self.model, id=id)
        return obj


class TaskListRawView(View):
    template_name = "task/task_list.html"
    queryset = TaskRepository().list()

    def get(self, request, *args, **kwargs):
        task_list = TaskRepository().list()
        paginator = Paginator(task_list, 8)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        view_context = {"page_obj": page_obj}
        return render(request, self.template_name, view_context)


class TaskCreateRawView(View):
    template_name = "task/task_create.html"  # DetailView

    def get(self, request, *args, **kwargs):
        # GET method
        form = TaskForm(error_class=DivErrorList)
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        # POST method
        form = TaskForm(request.POST, error_class=DivErrorList)
        if form.is_valid():
            add_task_service(
                form.cleaned_data["title"],
                form.cleaned_data["description"],
                form.cleaned_data["deadline_at"],
                form.cleaned_data["finished_at"],
                TaskRepository(),
                transaction.atomic(),
            )
            messages.success(self.request, "Task created successfully!")
            return HttpResponseRedirect(reverse("task:index"))
        context = {"form": form}
        return render(request, self.template_name, context)


class TaskUpdateRawView(TaskObjectMixin, View):
    template_name = "task/task_create.html"  # DetailView

    def get(self, request, id=None, *args, **kwargs):
        # GET method
        context = {}
        obj = self.get_object()
        form = TaskForm(instance=obj, error_class=DivErrorList)
        context["object"] = obj
        context["form"] = form
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        # POST method
        obj = self.get_object()
        form = TaskForm(request.POST, instance=obj, error_class=DivErrorList)
        if form.is_valid():
            update_task_service(
                obj.id,
                form.cleaned_data["title"],
                form.cleaned_data["description"],
                form.cleaned_data["deadline_at"],
                form.cleaned_data["finished_at"],
                TaskRepository(),
                transaction.atomic(),
            )            
            messages.success(self.request, "Task updated successfully!")
        return HttpResponseRedirect(reverse("task:detail", kwargs={"id": obj.id}))


class TaskDeleteRawView(TaskObjectMixin, View):
    template_name = "task/task_delete.html"  # DetailView

    def get(self, request, id=None, *args, **kwargs):
        # GET method
        obj = self.get_object()
        context = {"object": obj}
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        # POST method
        obj = self.get_object()
        detele_task_service(obj.id, 
                            TaskRepository(),
                            transaction.atomic())        
        messages.success(self.request, "Task deleted successfully!")
        return HttpResponseRedirect(reverse("task:index"))


class TaskDetailRawView(TaskObjectMixin, View):
    template_name = "task/task_detail.html"  # DetailView

    def get(self, request, id=None, *args, **kwargs):
        # GET method
        view_context = {"object": self.get_object()}
        return render(request, self.template_name, view_context)

todo/task/templates/task/task_create.html
{% extends 'base.html' %}
{% block content %}        
{% if form.instance.pk %}
<h1 class="ui header">UPDATE TASK</h1> 
{% else %}
    <h1 class="ui header">CREATE TASK</h1> 
{% endif %}
<form class="ui form" action="." method="POST" >      
    {% csrf_token %} 
    {{ form.as_p }}                          
    <input id="save_bt" type="submit" value="Save" class="ui green button">    
</form>
{% endblock %}

todo/task/templates/task/task_delete.html
{% extends 'base.html' %}
{% block content %}            
<form action='.' method='POST'>
    {% csrf_token %}
    <h1>Do you want to delete the post "{{ object.title }}"?</h1>    
    <p>
        <input type='submit' value='Yes' class="ui red button">
        <a href="{% url 'task:index' %}" class="ui button">Cancel</a>
    </p>
</form>    
{% endblock %}

todo/task/templates/task/task_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="ui main container">
    <h1 class="ui header">
        {{ object.title }}
        {% if object.finished_at %}
        <span class="ui green tiny label">finished</span>
        {% else %}
        <span class="ui orange tiny label">opend</span>
        {% endif %}
        {% if object.is_past_due %}
        <span class="ui red tiny label">overdue</span>
        {% endif %}
    </h1>
    <div class="meta">        
        <small>Created At: {{ object.created_at|default_if_none:"" }}</small><br>
        <small>Updated At: {{ object.updated_at|default_if_none:"" }}</small><br>
        <small class="ui text red">Deadline At: {{ object.deadline_at|default_if_none:"" }}</small><br>
        <small>Finished At: {{ object.finished_at|default_if_none:"" }}</small><br>   
    </div>
    <div class="text">
        Description: {{ object.description }}
        <div class="extra">                                            
            {% for tag in object.tag_list %}
            <div class="ui tiny label olive">{{ tag.slug }}</div>
            {% endfor %}
            <a href="{% url 'task:delete' id=object.id %}" class="ui right floated button red"><i class="close icon"></i>delete</a>
            <a href="{% url 'task:update' id=object.id %}" class="ui right floated button teal"><i class="edit icon"></i>edit</a>            
        </div>
    </div>        
</div>
{% endblock %}

todo/task/templates/task/task_list.html
{% extends 'base.html' %}
{% block content %}
<h1 class="ui header">
    TASKS        
</h1>
<div class="ui divided items">
    {% for task in page_obj %}
    <div class="item">
        <!-- <div class="ui small image"><img src="/images/wireframe/image.png"></div> -->
        <div class="middle aligned content">
            <h3 class="ui header">
                {{task.title}}
                {% if task.finished_at %}
                <span class="ui green mini label">finished</span>
                {% else %}
                <span class="ui orange mini label">opend</span>
                {% endif %}
                {% if task.is_past_due %}
                <span class="ui red mini label">overdue</span>
                {% endif %}
            </h3>
            <div class="extra ">
                <small>Created At {{task.created_at}} | Deadline At {{task.deadline_at}}</small>
            </div>            
            <div>{{task.description}}</div>
            <div class="extra">                                
                {% for tag in task.tag_list %}
                <div class="ui tiny label olive">{{ tag.slug }}</div>
                {% endfor %}                
                <a href="{% url 'task:delete' id=task.id %}" class="ui right floated button mini"><i
                        class="close icon"></i>delete</a>
                <a href="{% url 'task:update' id=task.id %}" class="ui right floated button mini"><i
                        class="edit icon"></i>edit</a>
                <a href="{{ task.get_absolute_url }}" class="ui right floated button mini"><i
                        class="eye icon"></i>view</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% if page_obj.paginator.num_pages > 1 %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a class="ui button mini" href="?page=1"><i class="angle double left icon"></i></a>
            <a class="ui button mini" href="?page={{ page_obj.previous_page_number }}"><i
                    class="angle left icon"></i></a>
            {% endif %}

            <span class="current">
                &nbsp;{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}&nbsp;
            </span>

            {% if page_obj.has_next %}
            <a class="ui button mini" href="?page={{ page_obj.next_page_number }}"><i class="angle right icon"></i></a>
            <a class="ui button mini" href="?page={{ page_obj.paginator.num_pages }}"><i
                    class="angle double right icon"></i></a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</div>
{% endblock %}