main/todo/urls.py
from django.urls import path


app_name = 'todo'

#########################################################
# Raw views
#########################################################

from .views.raw_views_classes import (    
    TaskCreateRawView,
    TaskDeleteRawView,
    TaskDetailRawView,
    TaskListRawView,      
    TaskUpdateRawView  
)

urlpatterns = [
    path('', TaskListRawView.as_view(), name='index'),
    path('create/', TaskCreateRawView.as_view(), name='create'),
    path('update/<int:id>/', TaskUpdateRawView.as_view(), name='update'),
    path('delete/<int:id>/', TaskDeleteRawView.as_view(), name='delete'),
    path('detail/<int:id>/', TaskDetailRawView.as_view(), name='detail')    
]

# #########################################################
# # Classes based views
# #########################################################

# from .views.classes_based_views import (
#     TaskCreateView,
#     TaskDeleteView,
#     TaskDetailView,
#     TaskListView,
#     TaskUpdateView
# )

# urlpatterns = [
#     path('', TaskListView.as_view(), name='index'),
#     path('create/', TaskCreateView.as_view(), name='create'),
#     path('update/<int:id>/', TaskUpdateView.as_view(), name='update'),
#     path('delete/<int:id>/', TaskDeleteView.as_view(), name='delete'),
#     path('detail/<int:id>/', TaskDetailView.as_view(), name='detail')    
# ]

#########################################################
# Functions based Views
#########################################################

# from .views.function_views import (     
#     list_view,
#     create_view, 
#     create_view_raw,
#     update_view ,
#     delete_view,
#     detail_view    
# )

# urlpatterns = [
#     path('', list_view, name='index'),
#     path('create/', create_view, name='create'),
#     path('createraw/', create_view_raw, name='createraw'),
#     path('update/<int:id>/', update_view, name='update'),
#     path('delete/<int:id>/', delete_view, name='delete'),
#     path('detail/<int:id>/', detail_view, name='detail')    
# ]

main/todo/templates/todo/task_delete.html
{% extends 'base.html' %}
{% block content %}        
    <main>        
        <form action='.' method='POST'>
            {% csrf_token %}
            <h1>Do you want to delete the post "{{ object.title }}"?</h1>
            <p><input type='submit' value='Yes' />  <a href="{% url 'todo:index' %}">Cancel</a></p>
        
        </form>
    </main>       
{% endblock %}

main/todo/templates/todo/task_list.html
{% extends 'base.html' %}
{% block content %}        
     <main>
        <ul>
            {% for task in object_list %}
            <li>
                {{ forloop.counter }} - {{task.title}}
                <br>                
                <a href="{{ task.get_absolute_url }}">View</a>
                <a href="{% url 'todo:update' id=task.id %}">Update</a>
                <a href="{% url 'todo:delete' id=task.id %}">Delete</a>            
                <br><br>
            </li>
            {% endfor %}
        </ul>
     </main>    
{% endblock %}