todo/apps/crontab_manager/urls.py
from django.urls import path


app_name = "crontab_manager"

from .views import (
    CronJobHomeView,    
    AddAllCronJobsView,
    RemoveAllCronJobsView,        
    RunCronJobView,
)

urlpatterns = [
    path("", CronJobHomeView.as_view(), name="home"),    
    path("add/", AddAllCronJobsView.as_view(), name="add"),    
    path("remove/", RemoveAllCronJobsView.as_view(), name="remove"),    
    path("run/<str:jobhash>/", RunCronJobView.as_view(), name="run"),
]

todo/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [ 
    path("", include("task.urls")), 
    path("crontab_manager/", include("django_crontab_manager.urls")), 
    path("admin/", admin.site.urls)
]

todo/apps/crontab_manager/views.py
from django import template
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import View

from .services import (
    get_cronjob_from_settings,
    get_cronjob_running,
    run_cronjob,
    add_all_cronjobs,
    remove_all_cronjobs,
)

register = template.Library()


class CronJobHomeView(View):
    template_name = "crontab_manager/home.html"

    def get(self, request, *args, **kwargs):
        view_context = {
            "settings_cronjobs": get_cronjob_from_settings(),
            "running_cronjobs": get_cronjob_running(),
        }
        return render(request, self.template_name, view_context)


class RunCronJobView(View):
    def get(self, request, *args, **kwargs):
        jobhash = self.kwargs.get("jobhash")
        run_cronjob(jobhash)
        messages.success(self.request, f"Running the {jobhash} cronjob")
        return HttpResponseRedirect(reverse("crontab_manager:home"))


class AddAllCronJobsView(View):
    def get(self, request, *args, **kwargs):
        add_all_cronjobs()
        messages.success(self.request, f"All cronjobs were removed from execution successfully!")
        return HttpResponseRedirect(reverse("crontab_manager:home"))


class RemoveAllCronJobsView(View):
    def get(self, request, *args, **kwargs):
        remove_all_cronjobs()
        messages.success(self.request, f"All cronjobs were removed successfully!")
        return HttpResponseRedirect(reverse("crontab_manager:home"))

todo/apps/crontab_manager/templates/crontab_manager/base.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>Pixeon Django Doilerplate</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">    
</head>

<body>
    {% include "crontab_manager/header.html" %}    
    <div class="ui main container" style="position: relative;">
        {% if messages %}        
            {% for message in messages %}
                <div class="ui positive message">
                    <i class="close icon"></i>
                    <div class="header">Success!</div>
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
        {% include "crontab_manager/footer.html" %}    
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <script src="{% static 'base/js/script.js' %}"></script>
</body>

</html>

todo/apps/crontab_manager/templates/crontab_manager/home.html
{% extends 'crontab_manager/base.html' %}
{% load lookup_dict %}
{% block content %}
<h1 class="ui header">CRONJOBS</h1>
<div class="ui divided items">
    <h4>FROM SETTINGS</h4>
    <table class="ui celled table">
        <thead class="full-width">
            <tr>
                <th>No.</th>
                <th>Job Hash</th>
                <th>Setting</th>                
            </tr>
        </thead>
        <tbody class="full-width">
            {% for jobhash,cronjob in settings_cronjobs.items %}
            <tr>
                <td data-label="no">{{forloop.counter}}</td>
                <td data-label="jobhash">{{jobhash}}</td>
                <td data-label="cronjob"><small>{{cronjob}}</small></td>                
            </tr>
            {% endfor %}
        </tbody>
        <tfoot class="full-width">
            <tr>
                <th></th>
                <th colspan="4">
                    <a href="{% url 'crontab_manager:add' %}" class="ui right floated small primary labeled icon button">
                        {% if running_cronjobs %}
                        <i class="caret square right icon"></i> Reload                        
                        {% else %}
                        <i class="caret square right icon"></i> Run All
                        {% endif %}
                    </a>
                </th>
            </tr>
        </tfoot>
    </table>
</div>

<div class="ui divided items">
    <h4>RUNNING</h4>
    <table class="ui celled table">
        <thead class="full-width">
            <tr>
                <th>No.</th>
                <th>Job Hash</th>
                <th>Setting</th>
                <th>Command</th>
                <th></th>
            </tr>
        </thead>
        <tbody class="full-width">
            {% for jobhash,cronjob in running_cronjobs.items %}
            <tr>
                <td data-label="no">{{forloop.counter}}</td>
                <td data-label="jobhash">{{jobhash}}</td>
                <td data-label="cronjob"><small>{{cronjob|lookup_dict:"setting"}}</small></td>
                <td data-label="cronjob"><small>{{cronjob|lookup_dict:"command"}}</small></td>
                <td data-label="actions">
                    <a href="{% url 'crontab_manager:run' jobhash=jobhash %}"
                        class="ui right floated mini positive labeled icon button">
                        <i class="caret square right icon"></i> Execute
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot class="full-width">
            <tr>
                <th></th>
                <th colspan="4">
                    <a href="{% url 'crontab_manager:remove' %}" class="ui right floated small negative labeled icon button">
                        <i class="user icon"></i> Remove All
                    </a>
                </th>
            </tr>
        </tfoot>
    </table>
</div>
{% endblock %}